# Site settings
title: Firoz Ansari
description: "My blog"
baseurl: ""
url: ""
# User settings
username: Firoz Ansari
user_title: Firoz Ansari
email: firozansar@gmail.com
twitter_username: firozansar
github_username:  firozansar
gplus_username:  FirozAnsari
disqus_username: firozansar

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: about me
    url: /about
# projects in header index
projects:
  - name: RedditReader(Android/Kotlin/MVVM)
    url: https://github.com/firozansar/RedditReader
  - name: MovieMVP (Android/Kotlin/MVP)
    url: https://github.com/firozansar/MovieMvp
  - name: RxWeatherApp (Android/Kotlin/MVVM)
    url: https://github.com/firozansar/RxWeatherApp  
  - name: Architecture Component Sample (Android/Kotlin/MVVM)
    url: https://github.com/firozansar/Architecture-Component-Sample
  - name: Coding exercise covering Android, Kotlin, MVVM, unit testing, UI testing
    url: https://github.com/firozansar/CodingExercise

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
